/**
 * Береста Workspace FS
 *
 * Manages the on-disk project workspace:
 *
 *   <root>/
 *   ├── norka.json           ← full project tree (IDs, titles, completedSteps)
 *   ├── DESIGN.md              ← Google Stitch–compatible design system doc
 *   ├── library/components/    ← per-component markdown
 *   └── projects/
 *       └── <productId>/
 *           ├── project.md     ← product context for LLM
 *           └── screens/
 *               └── <screenId>/
 *                   ├── screen.md
 *                   └── features/
 *                       └── <featureId>/
 *                           ├── analytics.md
 *                           ├── concept.tsx
 *                           ├── discussion.md
 *                           └── handoff.md
 *
 * All Tauri APIs are dynamically imported so the module safely loads in
 * the browser (IS_TAURI will be false and every operation is a no-op).
 */

import { ref, watch } from 'vue'

import { IS_TAURI } from '@/constants'
import { migrateLegacyLocalStorageValue } from '@/utils/local-storage'

import type { Product } from './use-projects'

// ── Types ─────────────────────────────────────────────────────────────────────

export type FeatureFile =
  | 'analytics.md'
  | 'analytics-source.md'
  | 'concept.tsx'
  | 'discussion.md'
  | 'handoff.md'
  | 'preview-layout.json'
  | 'feature-meta.json'
  | 'comments.json'
  | 'versions.json'
  | 'final-export.md'

export interface CoreRuntimeComponentSpec {
  id: string
  name: string
  importPath: string
  exportName: string
  description: string
  rules: string
  previewDefaults: Record<string, unknown>
}

export interface CoreRuntimeManifest {
  version: string
  generatedAt: string
  components: CoreRuntimeComponentSpec[]
}

export interface FeatureComment {
  id: string
  versionId: string
  status: 'open' | 'in_progress' | 'resolved'
  author: string
  text: string
  createdAt: string
  resolvedAt?: string
  resolvedInVersionId?: string
  nodeId?: string
  replies: Array<{ id: string; author: string; text: string; createdAt: string }>
}

export interface FeatureVersion {
  id: string
  title: string
  createdAt: string
  notes?: string
}

interface NorkaJson {
  version: '1'
  products: Product[]
}

// ── Singleton workspace path ───────────────────────────────────────────────────

const LS_WORKSPACE = 'norka:workspace-path'
const LS_FEATURE_FILE_PREFIX = 'norka:feature-file:'
const LEGACY_WORKSPACE_KEYS = ['bereста:workspacePath']

export const workspacePath = ref<string | null>(
  migrateLegacyLocalStorageValue(LS_WORKSPACE, LEGACY_WORKSPACE_KEYS)
)

watch(workspacePath, (v) => {
  if (v) localStorage.setItem(LS_WORKSPACE, v)
  else localStorage.removeItem(LS_WORKSPACE)
})

// ── Helpers ───────────────────────────────────────────────────────────────────

function join(...parts: string[]): string {
  return parts.join('/').replace(/\/+/g, '/')
}

function featureFileStorageKey(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string,
  file: FeatureFile
): string {
  return `${LS_FEATURE_FILE_PREFIX}${rootPath}:${productId}:${screenId}:${featureId}:${file}`
}

function readFeatureFileFromStorage(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string,
  file: FeatureFile
): string {
  try {
    return localStorage.getItem(featureFileStorageKey(rootPath, productId, screenId, featureId, file)) ?? ''
  } catch {
    return ''
  }
}

function writeFeatureFileToStorage(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string,
  file: FeatureFile,
  content: string
): void {
  try {
    localStorage.setItem(featureFileStorageKey(rootPath, productId, screenId, featureId, file), content)
  } catch (error) {
    console.warn('[workspace-fs] Failed to persist feature file cache.', error)
  }
}

async function ensureDir(path: string): Promise<void> {
  const { mkdir } = await import('@tauri-apps/plugin-fs')
  await mkdir(path, { recursive: true })
}

async function fileExists(path: string): Promise<boolean> {
  try {
    const { stat } = await import('@tauri-apps/plugin-fs')
    await stat(path)
    return true
  } catch {
    return false
  }
}

async function readText(path: string): Promise<string | null> {
  try {
    const { readTextFile } = await import('@tauri-apps/plugin-fs')
    return await readTextFile(path)
  } catch {
    return null
  }
}

async function writeText(path: string, content: string): Promise<void> {
  const { writeTextFile } = await import('@tauri-apps/plugin-fs')
  await writeTextFile(path, content)
}

// ── Default file templates ─────────────────────────────────────────────────────

function defaultDesignMd(): string {
  return `# DESIGN.md

<!-- Generated by Nork. Edit manually or regenerate from the Library workspace. -->
<!-- Format: Google Stitch DESIGN.md (9 sections) -->

## 1. Visual Theme & Atmosphere

<!-- Describe the overall mood, density, and design philosophy -->

## 2. Color Palette & Roles

| Token | Value | Role |
|-------|-------|------|
| \`primary\` | #3b82f6 | Actions, links, accents |
| \`surface\` | #ffffff | Content backgrounds |
| \`muted\` | #6b7280 | Secondary text |
| \`border\` | #e5e7eb | Dividers |
| \`error\` | #ef4444 | Errors, destructive |
| \`success\` | #10b981 | Confirmations |

## 3. Typography Rules

| Scale | Font | Size | Weight |
|-------|------|------|--------|
| h1 | Inter | 32px | 700 |
| h2 | Inter | 24px | 600 |
| body | Inter | 14px | 400 |
| caption | Inter | 12px | 400 |

## 4. Component Stylings

<!-- Describe buttons, cards, inputs, navigation with states -->

## 5. Layout Principles

- Base unit: 8px
- Spacing scale: 4, 8, 12, 16, 24, 32, 48, 64px
- Max content width: 1280px
- Gutter: 24px

## 6. Depth & Elevation

| Level | Shadow |
|-------|--------|
| 1 (card) | \`0 1px 3px #0000001f\` |
| 2 (dropdown) | \`0 4px 12px #00000029\` |
| 3 (modal) | \`0 8px 32px #0000003d\` |

## 7. Do's and Don'ts

**Do:**
- Use semantic color tokens, not raw hex values
- Maintain 4px grid alignment

**Don't:**
- Mix typefaces
- Use more than 3 levels of visual hierarchy per screen

## 8. Responsive Behavior

| Breakpoint | Width | Notes |
|------------|-------|-------|
| Mobile | < 768px | Single-column, touch targets ≥ 44px |
| Tablet | 768–1024px | Two columns |
| Desktop | > 1024px | Full layout |

## 9. Agent Prompt Guide

When generating UI with this design system:
- Use \`primary\` (#3b82f6) for CTAs
- Use 8px border-radius for cards, 6px for inputs, 4px for badges
- Prefer Inter font family
- Default spacing: 16px between sections, 8px within
`
}

function defaultProjectMd(title: string): string {
  return `# ${title}

## Описание продукта

<!-- Что делает этот продукт, его назначение -->

## Целевая аудитория

<!-- Кто пользуется, какие у них цели и боли -->

## Принципы дизайна

<!-- Ключевые UX-принципы, tone of voice -->

## Tech Stack

<!-- Фреймворки, платформы, ограничения -->

## Ссылки

<!-- Репозиторий, дизайн, аналитика, прочее -->
`
}

function defaultScreenMd(title: string): string {
  return `# Экран: ${title}

## Назначение

<!-- Что делает этот экран, основной user job -->

## Пользовательские сценарии

<!-- Главные задачи пользователя на этом экране -->

## Используемые компоненты

<!-- Компоненты из библиотеки, которые уже здесь -->

## Ограничения

<!-- Технические, дизайнерские или бизнес-ограничения -->
`
}

// ── Core API ──────────────────────────────────────────────────────────────────

/** Open OS folder-picker dialog; returns selected path or null */
export async function openWorkspaceDialog(): Promise<string | null> {
  if (!IS_TAURI) return null
  const { open } = await import('@tauri-apps/plugin-dialog')
  const result = await open({
    directory: true,
    multiple: false,
    title: 'Выберите папку рабочего пространства'
  })
  return typeof result === 'string' ? result : null
}

/** Read norka.json from workspace root → Product[] */
export async function readNorkaJson(rootPath: string): Promise<Product[] | null> {
  if (!IS_TAURI) return null
  const raw = await readText(join(rootPath, 'norka.json'))
  if (!raw) return null
  try {
    const data = JSON.parse(raw) as NorkaJson
    return data.products
  } catch {
    return null
  }
}

/** Write products to norka.json */
export async function writeNorkaJson(rootPath: string, products: Product[]): Promise<void> {
  if (!IS_TAURI) return
  const payload: NorkaJson = { version: '1', products }
  await writeText(join(rootPath, 'norka.json'), JSON.stringify(payload, null, 2))
}

/**
 * Ensure all folders and stub markdown files exist for the given product tree.
 * Safe to call on every save — only creates what's missing.
 */
export async function ensureWorkspaceStructure(
  rootPath: string,
  products: Product[]
): Promise<void> {
  if (!IS_TAURI) return

  // DESIGN.md
  const designMdPath = join(rootPath, 'DESIGN.md')
  if (!(await fileExists(designMdPath))) {
    await writeText(designMdPath, defaultDesignMd())
  }

  for (const product of products) {
    const productDir = join(rootPath, 'projects', product.id)
    await ensureDir(productDir)

    const projectMdPath = join(productDir, 'project.md')
    if (!(await fileExists(projectMdPath))) {
      await writeText(projectMdPath, defaultProjectMd(product.title))
    }

    for (const screen of product.screens) {
      const screenDir = join(productDir, 'screens', screen.id)
      await ensureDir(screenDir)

      const screenMdPath = join(screenDir, 'screen.md')
      if (!(await fileExists(screenMdPath))) {
        await writeText(screenMdPath, defaultScreenMd(screen.title))
      }

      for (const feature of screen.features) {
        const featureDir = join(screenDir, 'features', feature.id)
        await ensureDir(featureDir)
        const defaults: Array<[FeatureFile, string]> = [
          [
            'feature-meta.json',
            JSON.stringify(
              {
                jiraIssueKey: feature.jiraIssueKey ?? '',
                jiraUrl: feature.jiraUrl ?? '',
                designerFullName: feature.designerFullName ?? '',
                confluenceUrl: feature.confluenceUrl ?? ''
              },
              null,
              2
            )
          ],
          ['analytics.md', '# Аналитика\n\n<!-- Заполните аналитический бриф -->\n'],
          [
            'analytics-source.md',
            '# Analytics Source\n\n<!-- Paste source analytics from Confluence -->\n'
          ],
          ['comments.json', JSON.stringify([], null, 2)],
          [
            'versions.json',
            JSON.stringify(
              [
                {
                  id: 'v1',
                  title: 'v1',
                  createdAt: new Date().toISOString(),
                  notes: 'Initial version'
                }
              ],
              null,
              2
            )
          ]
        ]
        for (const [file, content] of defaults) {
          const filePath = join(featureDir, file)
          if (!(await fileExists(filePath))) {
            await writeText(filePath, content)
          }
        }
      }
    }
  }
}

/** Read DESIGN.md */
export async function readDesignMd(rootPath: string): Promise<string> {
  if (!IS_TAURI) return ''
  return (await readText(join(rootPath, 'DESIGN.md'))) ?? ''
}

/** Write DESIGN.md */
export async function writeDesignMd(rootPath: string, content: string): Promise<void> {
  if (!IS_TAURI) return
  await writeText(join(rootPath, 'DESIGN.md'), content)
}

/** Read project.md for a product */
export async function readProjectMd(rootPath: string, productId: string): Promise<string> {
  if (!IS_TAURI) return ''
  return (await readText(join(rootPath, 'projects', productId, 'project.md'))) ?? ''
}

/** Write project.md */
export async function writeProjectMd(
  rootPath: string,
  productId: string,
  content: string
): Promise<void> {
  if (!IS_TAURI) return
  await ensureDir(join(rootPath, 'projects', productId))
  await writeText(join(rootPath, 'projects', productId, 'project.md'), content)
}

/** Read screen.md */
export async function readScreenMd(
  rootPath: string,
  productId: string,
  screenId: string
): Promise<string> {
  if (!IS_TAURI) return ''
  return (
    (await readText(join(rootPath, 'projects', productId, 'screens', screenId, 'screen.md'))) ?? ''
  )
}

/** Write screen.md */
export async function writeScreenMd(
  rootPath: string,
  productId: string,
  screenId: string,
  content: string
): Promise<void> {
  if (!IS_TAURI) return
  await ensureDir(join(rootPath, 'projects', productId, 'screens', screenId))
  await writeText(join(rootPath, 'projects', productId, 'screens', screenId, 'screen.md'), content)
}

/** Read a feature file (analytics.md, concept.tsx, discussion.md, handoff.md) */
export async function readFeatureFile(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string,
  file: FeatureFile
): Promise<string> {
  if (!IS_TAURI) {
    return readFeatureFileFromStorage(rootPath, productId, screenId, featureId, file)
  }
  return (
    (await readText(
      join(rootPath, 'projects', productId, 'screens', screenId, 'features', featureId, file)
    )) ?? ''
  )
}

/** Write a feature file */
export async function writeFeatureFile(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string,
  file: FeatureFile,
  content: string
): Promise<void> {
  if (!IS_TAURI) {
    writeFeatureFileToStorage(rootPath, productId, screenId, featureId, file, content)
    return
  }
  const dir = join(rootPath, 'projects', productId, 'screens', screenId, 'features', featureId)
  await ensureDir(dir)
  await writeText(join(dir, file), content)
}

export async function readFeatureComments(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string
): Promise<FeatureComment[]> {
  const raw = await readFeatureFile(rootPath, productId, screenId, featureId, 'comments.json')
  if (!raw.trim()) return []
  try {
    const parsed = JSON.parse(raw) as FeatureComment[]
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

export async function writeFeatureComments(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string,
  comments: FeatureComment[]
): Promise<void> {
  await writeFeatureFile(
    rootPath,
    productId,
    screenId,
    featureId,
    'comments.json',
    JSON.stringify(comments, null, 2)
  )
}

export async function readFeatureVersions(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string
): Promise<FeatureVersion[]> {
  const raw = await readFeatureFile(rootPath, productId, screenId, featureId, 'versions.json')
  if (!raw.trim()) return []
  try {
    const parsed = JSON.parse(raw) as FeatureVersion[]
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

export async function writeFeatureVersions(
  rootPath: string,
  productId: string,
  screenId: string,
  featureId: string,
  versions: FeatureVersion[]
): Promise<void> {
  await writeFeatureFile(
    rootPath,
    productId,
    screenId,
    featureId,
    'versions.json',
    JSON.stringify(versions, null, 2)
  )
}

// ── Library component markdown ────────────────────────────────────────────────

/** Read a component spec markdown: <root>/library/components/<id>.md */
export async function readComponentMd(rootPath: string, id: string): Promise<string> {
  if (!IS_TAURI) return ''
  return (await readText(join(rootPath, 'library', 'components', `${id}.md`))) ?? ''
}

/** Write a component spec markdown */
export async function writeComponentMd(
  rootPath: string,
  id: string,
  content: string
): Promise<void> {
  if (!IS_TAURI) return
  const dir = join(rootPath, 'library', 'components')
  await ensureDir(dir)
  await writeText(join(dir, `${id}.md`), content)
}

/**
 * Read all component spec files, extract "## Правила" sections and return
 * a combined markdown string suitable for injecting into an AI system prompt.
 * Returns '' if the directory doesn't exist or no rules are found.
 */
export async function readAllComponentRules(rootPath: string): Promise<string> {
  if (!IS_TAURI) return ''
  try {
    const { readDir } = await import('@tauri-apps/plugin-fs')
    const dir = join(rootPath, 'library', 'components')
    const entries = await readDir(dir)
    const parts: string[] = []
    for (const entry of entries) {
      if (!entry.name.endsWith('.md')) continue
      const md = await readText(join(dir, entry.name))
      if (!md) continue
      // Extract component name from first line: # ComponentName
      const nameMatch = md.match(/^#\s+(.+)/m)
      const compName = nameMatch ? nameMatch[1].trim() : entry.name.replace('.md', '')
      // Extract ## Правила section
      const rulesMatch = md.match(/## Правила\s*\n([\s\S]*?)(?=\n## |$)/)
      if (rulesMatch?.[1].trim()) {
        parts.push(`## ${compName}\n${rulesMatch[1].trim()}`)
      }
    }
    return parts.length > 0 ? parts.join('\n\n') : ''
  } catch {
    return ''
  }
}

/** Minimal component spec needed for code export */
export interface CoreComponentSpec {
  id: string
  name: string
  primeReactImport: string
  primeReactExport: string
  description: string
  rules: string
}

function defaultPreviewPropsFor(name: string): Record<string, unknown> {
  switch (name) {
    case 'Button':
      return { label: 'Button', severity: 'primary' }
    case 'InputText':
      return { placeholder: 'Type here' }
    case 'Card':
      return { title: 'Card title', subTitle: 'Subtitle', children: 'Card content' }
    case 'Dialog':
      return { visible: true, header: 'Dialog', modal: false, children: 'Dialog content' }
    case 'Badge':
      return { value: 'Badge', severity: 'info' }
    case 'Avatar':
      return { label: 'AB', shape: 'circle' }
    case 'TabView':
      return { tabs: [{ header: 'Tab 1', content: 'Tab content' }] }
    case 'Dropdown':
      return {
        options: [
          { label: 'Option 1', value: '1' },
          { label: 'Option 2', value: '2' }
        ],
        optionLabel: 'label',
        placeholder: 'Select'
      }
    default:
      return {}
  }
}

function buildCoreRuntimeManifest(components: CoreComponentSpec[]): CoreRuntimeManifest {
  return {
    version: '1',
    generatedAt: new Date().toISOString(),
    components: components.map((comp) => ({
      id: comp.id,
      name: comp.name,
      importPath: comp.primeReactImport,
      exportName: comp.primeReactExport,
      description: comp.description,
      rules: comp.rules,
      previewDefaults: defaultPreviewPropsFor(comp.primeReactExport)
    }))
  }
}

export function validateCoreRuntimeManifest(
  manifest: CoreRuntimeManifest
): { ok: true } | { ok: false; errors: string[] } {
  const errors: string[] = []
  if (manifest.version !== '1') errors.push('Unsupported manifest version')
  if (!Array.isArray(manifest.components) || manifest.components.length === 0) {
    errors.push('No components in runtime manifest')
  }
  for (const comp of manifest.components) {
    if (!comp.id) errors.push('Component with empty id')
    if (!comp.exportName) errors.push(`Component "${comp.id}" has empty exportName`)
    if (!comp.importPath) errors.push(`Component "${comp.id}" has empty importPath`)
  }
  return errors.length === 0 ? { ok: true } : { ok: false, errors }
}

export async function readCoreRuntimeManifest(
  rootPath: string
): Promise<CoreRuntimeManifest | null> {
  if (!IS_TAURI) return null
  const raw = await readText(join(rootPath, 'core', 'runtime-manifest.json'))
  if (!raw) return null
  try {
    const parsed = JSON.parse(raw) as CoreRuntimeManifest
    const validation = validateCoreRuntimeManifest(parsed)
    return validation.ok ? parsed : null
  } catch {
    return null
  }
}

/**
 * Export Core Library as TSX files to <root>/core/.
 * Creates:
 *   core/<Name>.tsx   — re-export from PrimeReact + rules as jsdoc
 *   core/index.ts     — barrel re-exports
 *   core/README.md    — component table + rules
 */
export async function exportCoreComponents(
  rootPath: string,
  components: CoreComponentSpec[]
): Promise<void> {
  if (!IS_TAURI) return
  const coreDir = join(rootPath, 'core')
  await ensureDir(coreDir)

  for (const comp of components) {
    const rulesLines = comp.rules
      ? comp.rules
          .split('\n')
          .filter(Boolean)
          .map((l) => ` * ${l}`)
          .join('\n')
      : ' * (нет правил)'

    const content = [
      `// Generated by Береста Core Library — DO NOT EDIT`,
      `// Source: library/components/${comp.id}.md`,
      `//`,
      `// ${comp.description}`,
      `//`,
      `// Rules:`,
      rulesLines,
      ``,
      `export { ${comp.primeReactExport} } from '${comp.primeReactImport}'`,
      `export type { ${comp.primeReactExport}Props } from '${comp.primeReactImport}'`,
      ``
    ].join('\n')

    await writeText(join(coreDir, `${comp.primeReactExport}.tsx`), content)
  }

  // index.ts
  const indexLines = [
    `// Generated by Береста Core Library — DO NOT EDIT`,
    ``,
    ...components.map((c) => `export { ${c.primeReactExport} } from './${c.primeReactExport}'`),
    ``
  ]
  await writeText(join(coreDir, 'index.ts'), indexLines.join('\n'))

  // README.md
  const tableRows = components.map(
    (c) => `| \`${c.name}\` | \`${c.primeReactImport}\` | ${c.description} |`
  )
  const readmeLines = [
    `# Core Library`,
    ``,
    `> Generated by Береста. Source of truth: \`library/components/\``,
    ``,
    `## Компоненты`,
    ``,
    `| Компонент | PrimeReact | Описание |`,
    `|-----------|-----------|----------|`,
    ...tableRows,
    ``,
    `## Правила использования`,
    ``,
    ...components.flatMap((c) => [
      `### ${c.name}`,
      ``,
      ...(c.rules ? c.rules.split('\n').filter(Boolean) : ['(нет правил)']),
      ``
    ])
  ]
  await writeText(join(coreDir, 'README.md'), readmeLines.join('\n'))

  // runtime-manifest.json
  const runtimeManifest = buildCoreRuntimeManifest(components)
  await writeText(join(coreDir, 'runtime-manifest.json'), JSON.stringify(runtimeManifest, null, 2))
}

// ── Composable (reactive wrapper) ─────────────────────────────────────────────

export function useWorkspaceFs() {
  return {
    workspacePath,
    isDesktop: IS_TAURI,
    openWorkspaceDialog,
    readNorkaJson,
    writeNorkaJson,
    ensureWorkspaceStructure,
    readDesignMd,
    writeDesignMd,
    readProjectMd,
    writeProjectMd,
    readScreenMd,
    writeScreenMd,
    readFeatureFile,
    writeFeatureFile,
    readFeatureComments,
    writeFeatureComments,
    readFeatureVersions,
    writeFeatureVersions,
    readComponentMd,
    writeComponentMd,
    readAllComponentRules,
    readCoreRuntimeManifest,
    exportCoreComponents
  }
}
