/**
 * Береста Workspace FS
 *
 * Manages the on-disk project workspace:
 *
 *   <root>/
 *   ├── beresta.json           ← full project tree (IDs, titles, completedSteps)
 *   ├── DESIGN.md              ← Google Stitch–compatible design system doc
 *   ├── library/components/    ← per-component markdown
 *   └── projects/
 *       └── <productId>/
 *           ├── project.md     ← product context for LLM
 *           └── screens/
 *               └── <screenId>/
 *                   ├── screen.md
 *                   └── features/
 *                       └── <featureId>/
 *                           ├── analytics.md
 *                           ├── concept.tsx
 *                           ├── discussion.md
 *                           └── handoff.md
 *
 * All Tauri APIs are dynamically imported so the module safely loads in
 * the browser (IS_TAURI will be false and every operation is a no-op).
 */

import { ref, watch } from 'vue'
import { IS_TAURI } from '@/constants'
import type { Product } from './use-projects'

// ── Types ─────────────────────────────────────────────────────────────────────

export type FeatureFile = 'analytics.md' | 'concept.tsx' | 'discussion.md' | 'handoff.md'

interface BerestaJson {
  version: '1'
  products: Product[]
}

// ── Singleton workspace path ───────────────────────────────────────────────────

const LS_WORKSPACE = 'bereста:workspacePath'

export const workspacePath = ref<string | null>(localStorage.getItem(LS_WORKSPACE))

watch(workspacePath, (v) => {
  if (v) localStorage.setItem(LS_WORKSPACE, v)
  else localStorage.removeItem(LS_WORKSPACE)
})

// ── Helpers ───────────────────────────────────────────────────────────────────

function join(...parts: string[]): string {
  return parts.join('/').replace(/\/+/g, '/')
}

async function ensureDir(path: string): Promise<void> {
  const { mkdir } = await import('@tauri-apps/plugin-fs')
  await mkdir(path, { recursive: true })
}

async function fileExists(path: string): Promise<boolean> {
  try {
    const { stat } = await import('@tauri-apps/plugin-fs')
    await stat(path)
    return true
  } catch {
    return false
  }
}

async function readText(path: string): Promise<string | null> {
  try {
    const { readTextFile } = await import('@tauri-apps/plugin-fs')
    return await readTextFile(path)
  } catch {
    return null
  }
}

async function writeText(path: string, content: string): Promise<void> {
  const { writeTextFile } = await import('@tauri-apps/plugin-fs')
  await writeTextFile(path, content)
}

// ── Default file templates ─────────────────────────────────────────────────────

function defaultDesignMd(): string {
  return `# DESIGN.md

<!-- Generated by Nork. Edit manually or regenerate from the Library workspace. -->
<!-- Format: Google Stitch DESIGN.md (9 sections) -->

## 1. Visual Theme & Atmosphere

<!-- Describe the overall mood, density, and design philosophy -->

## 2. Color Palette & Roles

| Token | Value | Role |
|-------|-------|------|
| \`primary\` | #3b82f6 | Actions, links, accents |
| \`surface\` | #ffffff | Content backgrounds |
| \`muted\` | #6b7280 | Secondary text |
| \`border\` | #e5e7eb | Dividers |
| \`error\` | #ef4444 | Errors, destructive |
| \`success\` | #10b981 | Confirmations |

## 3. Typography Rules

| Scale | Font | Size | Weight |
|-------|------|------|--------|
| h1 | Inter | 32px | 700 |
| h2 | Inter | 24px | 600 |
| body | Inter | 14px | 400 |
| caption | Inter | 12px | 400 |

## 4. Component Stylings

<!-- Describe buttons, cards, inputs, navigation with states -->

## 5. Layout Principles

- Base unit: 8px
- Spacing scale: 4, 8, 12, 16, 24, 32, 48, 64px
- Max content width: 1280px
- Gutter: 24px

## 6. Depth & Elevation

| Level | Shadow |
|-------|--------|
| 1 (card) | \`0 1px 3px rgba(0,0,0,.12)\` |
| 2 (dropdown) | \`0 4px 12px rgba(0,0,0,.16)\` |
| 3 (modal) | \`0 8px 32px rgba(0,0,0,.24)\` |

## 7. Do's and Don'ts

**Do:**
- Use semantic color tokens, not raw hex values
- Maintain 4px grid alignment

**Don't:**
- Mix typefaces
- Use more than 3 levels of visual hierarchy per screen

## 8. Responsive Behavior

| Breakpoint | Width | Notes |
|------------|-------|-------|
| Mobile | < 768px | Single-column, touch targets ≥ 44px |
| Tablet | 768–1024px | Two columns |
| Desktop | > 1024px | Full layout |

## 9. Agent Prompt Guide

When generating UI with this design system:
- Use \`primary\` (#3b82f6) for CTAs
- Use 8px border-radius for cards, 6px for inputs, 4px for badges
- Prefer Inter font family
- Default spacing: 16px between sections, 8px within
`
}

function defaultProjectMd(title: string): string {
  return `# ${title}

## Описание продукта

<!-- Что делает этот продукт, его назначение -->

## Целевая аудитория

<!-- Кто пользуется, какие у них цели и боли -->

## Принципы дизайна

<!-- Ключевые UX-принципы, tone of voice -->

## Tech Stack

<!-- Фреймворки, платформы, ограничения -->

## Ссылки

<!-- Репозиторий, дизайн, аналитика, прочее -->
`
}

function defaultScreenMd(title: string): string {
  return `# Экран: ${title}

## Назначение

<!-- Что делает этот экран, основной user job -->

## Пользовательские сценарии

<!-- Главные задачи пользователя на этом экране -->

## Используемые компоненты

<!-- Компоненты из библиотеки, которые уже здесь -->

## Ограничения

<!-- Технические, дизайнерские или бизнес-ограничения -->
`
}

// ── Core API ──────────────────────────────────────────────────────────────────

/** Open OS folder-picker dialog; returns selected path or null */
export async function openWorkspaceDialog(): Promise<string | null> {
  if (!IS_TAURI) return null
  const { open } = await import('@tauri-apps/plugin-dialog')
  const result = await open({ directory: true, multiple: false, title: 'Выберите папку рабочего пространства' })
  return typeof result === 'string' ? result : null
}

/** Read beresta.json from workspace root → Product[] */
export async function readBerestaJson(rootPath: string): Promise<Product[] | null> {
  if (!IS_TAURI) return null
  const raw = await readText(join(rootPath, 'beresta.json'))
  if (!raw) return null
  try {
    const data = JSON.parse(raw) as BerestaJson
    return data.products ?? null
  } catch {
    return null
  }
}

/** Write products to beresta.json */
export async function writeBerestaJson(rootPath: string, products: Product[]): Promise<void> {
  if (!IS_TAURI) return
  const payload: BerestaJson = { version: '1', products }
  await writeText(join(rootPath, 'beresta.json'), JSON.stringify(payload, null, 2))
}

/**
 * Ensure all folders and stub markdown files exist for the given product tree.
 * Safe to call on every save — only creates what's missing.
 */
export async function ensureWorkspaceStructure(rootPath: string, products: Product[]): Promise<void> {
  if (!IS_TAURI) return

  // DESIGN.md
  const designMdPath = join(rootPath, 'DESIGN.md')
  if (!(await fileExists(designMdPath))) {
    await writeText(designMdPath, defaultDesignMd())
  }

  for (const product of products) {
    const productDir = join(rootPath, 'projects', product.id)
    await ensureDir(productDir)

    const projectMdPath = join(productDir, 'project.md')
    if (!(await fileExists(projectMdPath))) {
      await writeText(projectMdPath, defaultProjectMd(product.title))
    }

    for (const screen of product.screens) {
      const screenDir = join(productDir, 'screens', screen.id)
      await ensureDir(screenDir)

      const screenMdPath = join(screenDir, 'screen.md')
      if (!(await fileExists(screenMdPath))) {
        await writeText(screenMdPath, defaultScreenMd(screen.title))
      }

      for (const feature of screen.features) {
        const featureDir = join(screenDir, 'features', feature.id)
        await ensureDir(featureDir)
      }
    }
  }
}

/** Read DESIGN.md */
export async function readDesignMd(rootPath: string): Promise<string> {
  if (!IS_TAURI) return ''
  return (await readText(join(rootPath, 'DESIGN.md'))) ?? ''
}

/** Write DESIGN.md */
export async function writeDesignMd(rootPath: string, content: string): Promise<void> {
  if (!IS_TAURI) return
  await writeText(join(rootPath, 'DESIGN.md'), content)
}

/** Read project.md for a product */
export async function readProjectMd(rootPath: string, productId: string): Promise<string> {
  if (!IS_TAURI) return ''
  return (await readText(join(rootPath, 'projects', productId, 'project.md'))) ?? ''
}

/** Write project.md */
export async function writeProjectMd(rootPath: string, productId: string, content: string): Promise<void> {
  if (!IS_TAURI) return
  await ensureDir(join(rootPath, 'projects', productId))
  await writeText(join(rootPath, 'projects', productId, 'project.md'), content)
}

/** Read screen.md */
export async function readScreenMd(rootPath: string, productId: string, screenId: string): Promise<string> {
  if (!IS_TAURI) return ''
  return (await readText(join(rootPath, 'projects', productId, 'screens', screenId, 'screen.md'))) ?? ''
}

/** Write screen.md */
export async function writeScreenMd(rootPath: string, productId: string, screenId: string, content: string): Promise<void> {
  if (!IS_TAURI) return
  await ensureDir(join(rootPath, 'projects', productId, 'screens', screenId))
  await writeText(join(rootPath, 'projects', productId, 'screens', screenId, 'screen.md'), content)
}

/** Read a feature file (analytics.md, concept.tsx, discussion.md, handoff.md) */
export async function readFeatureFile(
  rootPath: string, productId: string, screenId: string, featureId: string, file: FeatureFile,
): Promise<string> {
  if (!IS_TAURI) return ''
  return (
    await readText(join(rootPath, 'projects', productId, 'screens', screenId, 'features', featureId, file))
  ) ?? ''
}

/** Write a feature file */
export async function writeFeatureFile(
  rootPath: string, productId: string, screenId: string, featureId: string, file: FeatureFile, content: string,
): Promise<void> {
  if (!IS_TAURI) return
  const dir = join(rootPath, 'projects', productId, 'screens', screenId, 'features', featureId)
  await ensureDir(dir)
  await writeText(join(dir, file), content)
}

// ── Composable (reactive wrapper) ─────────────────────────────────────────────

export function useWorkspaceFs() {
  return {
    workspacePath,
    isDesktop: IS_TAURI,
    openWorkspaceDialog,
    readBerestaJson,
    writeBerestaJson,
    ensureWorkspaceStructure,
    readDesignMd,
    writeDesignMd,
    readProjectMd,
    writeProjectMd,
    readScreenMd,
    writeScreenMd,
    readFeatureFile,
    writeFeatureFile,
  }
}
